### PR TITLE
TokenRouter Urgent Bug Fix & Added Method Filtering to TokenRouter 

### PR DESCRIPTION
**Pull request by gerardtoconnor**
To be more consistent and not need choose have added method filter routing functions.

Have also fixed a bug for fringe case not identified before.

### CODE REVIEW

**Comment by forki** [comment]
Since this hit us, I'm very happy to see it fixed

**Comment by forki** [comment]
can you please check the following:

let webApp =
    let notfound = NOT_FOUND "Page not found"
    choose [
        GET >=>
            router notfound [
                route "/" (text "hello")
                subRoute "/ocpp" [
                    subRoute "/v15" [
                        route "/BootNotification" (text "hello")
                    ]
                ]
            ]
    ]


/ work
/ocpp/v15/BootNotification does not

**Comment by forki** [comment]
route "/ocpp/v15" (text "hello")
                route "/ocpp/v15/BootNotification" (text "hello")

with this I get 404 on /ocpp/v15

**Comment by gerardtoconnor** [comment]
I added test for the below (note the change in method filtering) and it finds hello on 
"/ocpp/v15/BootNotification"  path correctly

please use build of my `route-method` branch if update needed immediately, not sure when @dustinmoris will be able to merge this update/fix 
```f#
let webApp =
    let notfound = NOT_FOUND "Page not found"
    router notFound [
            GET [
                route "/" (text "hello")
                subRoute "/ocpp" [
                    subRoute "/v15" [
                        route "/BootNotification" (text "hello")
                    ]
                ]                    
            ]
    ]

**Comment by gerardtoconnor** [comment]
I have also added a `portRoute` HttpHandler so users can route by port on requests and split their apps into separate domains. Tests have also been added as well as updating of README 

appveyor failing due to some dir copy issue, builds fine on my machine and travis

**Comment by gerardtoconnor** [comment]
@dustinmoris are you able to merge this asap as there is a bad bug effecting users that this PR addresses, if you are unsure on Method Filter / Port Handler, please let me know and I'll strip out but need the Bug fix through. thanks.

**Comment by gerardtoconnor** [comment]
Thanks @dustinmoris

**Comment by dustinmoris** [comment]
np, release coming up in the next few minutes!

**Pull request merged**
