### PR TITLE
[RFC] Add ability to customize JSON serializer settings

### PR DESCRIPTION
**Pull request by maxdeviant**
Currently the `json` HTTP handler will always use the default JSON serializer settings.

It is possible to change them by directly modifying `JsonConvert.DefaultSettings`, but since this will change the settings globally there are some cases where this is undesirable. It would be much better to be able to customize the serializer settings on a case-by-case basis.

From an API standpoint, do we want to make this the default for `json`? Or should there be something like a `customJson` that someone can use if they want to opt-in to this functionality?

### CODE REVIEW

**Comment by maxdeviant** [comment]
@dustinmoris Would like to get your input before I go too far down this path :smile:

**Comment by dustinmoris** [comment]
Hi, first of all sorry that I am getting back a bit delayed. I am abroad and was in a place without WiFi for the last two days :(. Secondly I think what you say makes sense and there should be a way to customise the JSON serialisation.

I like your changes, but I am wondering if the `customJson` is even needed or if it wouldn't be better to expose the `makeJsonHandler` publicly so that a user could initilize a custom serializer only once and then create a handler with it themselves which they could name whichever way they like.

Not sure, what do you think?

**Comment by maxdeviant** [comment]
@dustinmoris No worries!

Exposing `makeJsonHandler` is actually how I would prefer to do it, but I also wasn't sure if that aligned with your vision of the public API for Giraffe. But this is exactly why I asked :smile:

I'll ping you once I've cleaned some things up and gotten the tests passing.

**Comment by dustinmoris** [comment]
Hi, how are you getting on with this? If there's anything I can do let me know, otherwise I'll wait for you to clean up the stuff as you suggested :)

**Comment by maxdeviant** [comment]
@dustinmoris Been pretty busy with work lately, so I haven't had any time to look at it. But I'll let you know if you have any questions on it.

**Comment by dustinmoris** [comment]
@maxdeviant sure no rush... I really just wanted to make sure you were not waiting for me on anything :) Thanks for your help!

**Comment by dustinmoris** [comment]
Hi, just FYI I think this is an important change which I would like to get completed before I consider Giraffe RC ready. Please let me know if you think you still want to work on this PR otherwise I can take over from here and finish it :)

**Comment by maxdeviant** [comment]
@dustinmoris Sure thing! I'll see if I can get it merge-ready in the next couple of days.

**Comment by maxdeviant** [comment]
@dustinmoris Sorry for the delay on this. I haven't had the time to focus on it, so it might be better if you take over.

**Comment by dustinmoris** [comment]
Done by @KerryRJ in #146

**Pull request closed without merging**
