### PR TITLE
#57 build on linux

### LINKED ISSUE #57: Build on linux
This project should also have a build on travis for linux mono/dotnetcore.  I'll submit a PR with the travis file and `build.sh`  Probably don't need all of these but a small subset like mono 5.0 and 4.8 https://github.com/TheAngryByrd/Chessie.Hopac/blob/master/.travis.yml

I know `dotnet test` fails on mono https://github.com/Microsoft/vstest/issues/445 https://github.com/Microsoft/vstest/issues/679 however if we use `dotnet xunit` https://www.nuget.org/packages/dotnet-xunit/2.3.0-beta2-build3683 I added support for mono awhile ago https://github.com/xunit/xunit/pull/1213

### PR DESCRIPTION
**Pull request by TheAngryByrd**
Closes #57

Added a bare bones `./build.sh` file.  Might want to consider using something like FAKE to do builds cross platform and only have to maintain one file.

Added `.travis-ci.yml` with targets of mono 4.6.1, 4.8.1 and 5.0.1 and dotnet core 1.0.1.  

When running tests for net46, I am getting this error:

```
Running desktop CLR tests for framework net46...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: Giraffe.Tests
  Discovered:  Giraffe.Tests
  Starting:    Giraffe.Tests
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml, application/json" returns XML object [FAIL]
      Assert.Equal() Failure
                                   ↓ (pos 19)
      Expected: <?xml version="1.0" encoding="utf-8"?>\n<Person xmlns:xsi="ht···
      Actual:   <?xml version="1.0"?>\n<Person xmlns:xsd="http://www.w3.org/2···
                                   ↑ (pos 19)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml, application/json" returns XML object () [0x00218] in <593f35f7ac43ffeaa7450383f7353f59>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml; q=0.6" returns XML object [FAIL]
      Assert.Equal() Failure
                                   ↓ (pos 19)
      Expected: <?xml version="1.0" encoding="utf-8"?>\n<Person xmlns:xsi="ht···
      Actual:   <?xml version="1.0"?>\n<Person xmlns:xsd="http://www.w3.org/2···
                                   ↑ (pos 19)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml; q=0.6" returns XML object () [0x00218] in <593f35f7ac43ffeaa7450383f7353f59>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml" returns XML object [FAIL]
      Assert.Equal() Failure
                                   ↓ (pos 19)
      Expected: <?xml version="1.0" encoding="utf-8"?>\n<Person xmlns:xsi="ht···
      Actual:   <?xml version="1.0"?>\n<Person xmlns:xsd="http://www.w3.org/2···
                                   ↑ (pos 19)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml" returns XML object () [0x00218] in <593f35f7ac43ffeaa7450383f7353f59>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml" returns XML object [FAIL]
      Assert.Equal() Failure
                                   ↓ (pos 19)
      Expected: <?xml version="1.0" encoding="utf-8"?>\n<Person xmlns:xsi="ht···
      Actual:   <?xml version="1.0"?>\n<Person xmlns:xsd="http://www.w3.org/2···
                                   ↑ (pos 19)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml" returns XML object () [0x00218] in <593f35f7ac43ffeaa7450383f7353f59>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  Finished:    Giraffe.Tests

```

~~Can someone confirm this is happening on windows too?~~

Looks like it fails on Windows too via appveyor.  Yay unit tests!

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
Seems like the test failure is due to a difference with `XmlSerializer` on core vs full.

**Comment by nojaf** [comment]
I believe it is the newline character that is different on Windows. I actually had this as well a while ago on Windows as well. Some tests were failing.

Perhaps if the xml in https://github.com/dustinmoris/Giraffe/blob/develop/tests/Giraffe.Tests/HttpHandlerTests.fs#L1032 were to be stripped of the [Environment.NewLine](https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline?view=netcore-1.1#System_Environment_NewLine).

**Comment by dustinmoris** [comment]
Yes I often had the issue with line breaks as well, but in this instance it is actually a difference in the implementation of the `XmlSerializer`:

```
Expected: <?xml version="1.0" encoding="utf-8"?>\n<Person xmlns:xsi="ht···
Actual:   <?xml version="1.0"?>\n<Person xmlns:xsd="http://www.w3.org/2···
```

Mono doesn't add the `encoding` attribute as it is done by the original .NET and .NET Core implementation.

**Comment by dustinmoris** [comment]
I haven't tried it yet, but perhaps this can be fixed by specifying the encoding during the serialization:

```
let serializeXml x =
    let serializer = XmlSerializer(x.GetType())
    use stream = new MemoryStream()
    use writer = new StreamWriter(stream, System.Text.Encoding.UTF8)
    serializer.Serialize(writer, x)
    stream.ToArray()
```

**Comment by dustinmoris** [comment]
Regarding one build script for all environments I would prefer to install PowerShell in one of the pre build steps on Travis and then use the existing build script: https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1404

**Comment by TheAngryByrd** [comment]
`XmlSerializer` doesn't seem like a mono specific issue as the appveyor build has the same problem. More of a core vs full issue.

I did the work to add encoding to the top but the xml is still slightly different:

```
    use stream = new MemoryStream()
    let xmlWriterSettings = XmlWriterSettings(Encoding= Encoding.UTF8, Indent = true, OmitXmlDeclaration=false )
    use xmlWriter = XmlWriter.Create(stream, xmlWriterSettings)
    let serializer = XmlSerializer(x.GetType())
    serializer.Serialize(xmlWriter, x)
    stream.ToArray()
```

```
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: Giraffe.Tests
  Discovered:  Giraffe.Tests
  Starting:    Giraffe.Tests
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml, application/json" returns XML object [FAIL]
      Assert.Equal() Failure
                                        ↓ (pos 55)
      Expected: ···"?>\n<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   ···"?>\n<Person xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                        ↑ (pos 55)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml, application/json" returns XML object () [0x00218] in <59400d85a332fb92a7450383850d4059>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml; q=0.6" returns XML object [FAIL]
      Assert.Equal() Failure
                                        ↓ (pos 55)
      Expected: ···"?>\n<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   ···"?>\n<Person xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                        ↑ (pos 55)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml; q=0.6" returns XML object () [0x00218] in <59400d85a332fb92a7450383850d4059>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml" returns XML object [FAIL]
      Assert.Equal() Failure
                                        ↓ (pos 55)
      Expected: ···"?>\n<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   ···"?>\n<Person xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                        ↑ (pos 55)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/json; q=0.5, application/xml" returns XML object () [0x00218] in <59400d85a332fb92a7450383850d4059>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
    Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml" returns XML object [FAIL]
      Assert.Equal() Failure
                                        ↓ (pos 55)
      Expected: ···"?>\n<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta···
      Actual:   ···"?>\n<Person xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln···
                                        ↑ (pos 55)
      Stack Trace:
          at Giraffe.HttpHandlerTests.Get "/auto" with Accept header of "application/xml" returns XML object () [0x00218] in <59400d85a332fb92a7450383850d4059>:0 
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  Finished:    Giraffe.Tests

```

---

I'd caution on forcing contributors from osx/linux to need powershell to do builds.  I've just seen similar struggles with ruby as a build system, but it's your call.

**Comment by dustinmoris** [comment]
Oh yes you are right, I didn't see that the AppVeyor build failed as well. Looks like the encoding issue has been fixed by that change but the XML attribute for the namespace is slightly different. I think there was an option to set the namespace as well as part of the XmlSerializer. If that doesn't work then we should probably do a #if #endif switch for the expected result?

**Comment by TheAngryByrd** [comment]
Yeah it's failing because some attributes are out of order


```
"<?xml version="1.0" encoding="utf-8"?>
<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <FirstName>John</FirstName>
  <LastName>Doe</LastName>
  <BirthDate>1990-07-12T00:00:00</BirthDate>
  <Height>1.85</Height>
  <Piercings>
    <string>ear</string>
    <string>nose</string>
  </Piercings>
</Person>"
```
vs
```
"<?xml version="1.0" encoding="utf-8"?>
<Person xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <FirstName>John</FirstName>
  <LastName>Doe</LastName>
  <BirthDate>1990-07-12T00:00:00</BirthDate>
  <Height>1.85</Height>
  <Piercings>
    <string>ear</string>
    <string>nose</string>
  </Piercings>
</Person>"
```

We could either ifdef it, or go down the path of comparing xml documents which https://msdn.microsoft.com/en-us/library/system.xml.linq.xnode.deepequals(v=vs.110).aspx outlines a just a bit tad more work.

**Comment by TheAngryByrd** [comment]
It was actually pretty easy to implement for this case:

https://weblogs.asp.net/marianor/easy-way-to-compare-two-xmls-for-equality

```

module XmlAssert =
    open System.Linq
    open System.Xml
    open System.Xml.Linq
    let rec normalize (element : XElement) =
        if element.HasElements then
            XElement(
                element.Name,
                element.Attributes()
                    .Where(fun a -> a.Name.Namespace = XNamespace.Xmlns)
                    .OrderBy(fun a -> a.Name.ToString()),
                element.Elements().OrderBy(fun a -> a.Name.ToString())
                    .Select(fun e -> normalize(e))
            )
        elif element.IsEmpty then  
            XElement(
                element.Name, 
                element.Attributes()
                    .OrderBy(fun a -> a.Name.ToString())
              )
         else
            XElement(
                element.Name, 
                element.Attributes()
                    .OrderBy(fun a -> a.Name.ToString()), element.Value
               )

    let equals expectedXml actualXml =
        let expectedXElement = XElement.Parse expectedXml |> normalize
        let actualXElement = XElement.Parse actualXml |> normalize
        Assert.Equal(expectedXElement.ToString(), actualXElement.ToString())
```


This solves the xml issue.  Would you like these changes submitted with this PR as well?

**Comment by dustinmoris** [comment]
Yes please, that is great!

**Comment by TheAngryByrd** [comment]
As I mentioned in #57 `dotnet test` doesn't support mono yet https://github.com/Microsoft/vstest/issues/679 😿 .  `dotnet-xunit` won't work unless xunit lib is up to 2.3.0.  The pain of the new dotnet tooling.  

The other option is to only test on `netcoreapp1.x` on linux for now.

**Comment by TheAngryByrd** [comment]
Also could you enable travis?

**Comment by dustinmoris** [comment]
Turned it on now. Ok, let's test on netcoreapp1.x for now. I will file an issue with xunit.

**Comment by TheAngryByrd** [comment]
*sigh*

```
Starting test execution, please wait...
[xUnit.net 00:00:00.8990631]   Discovering: SampleApp.Tests
[xUnit.net 00:00:01.0605466]   Discovered:  SampleApp.Tests
[xUnit.net 00:00:01.1193957]   Starting:    SampleApp.Tests
[xUnit.net 00:00:02.5829673]     Tests.Test /razor returns html content [FAIL]
[xUnit.net 00:00:02.5876579]       System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
[xUnit.net 00:00:02.5902555]       Stack Trace:
[xUnit.net 00:00:02.5927425]            at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
[xUnit.net 00:00:02.5932724]            at Tests.ensureSuccess(HttpResponseMessage response)
[xUnit.net 00:00:02.5939279]            at Tests.Test /razor returns html content()
[xUnit.net 00:00:02.6302964]   Finished:    SampleApp.Tests
Failed   Tests.Test /razor returns html content
Error Message:
 System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).
Stack Trace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Tests.ensureSuccess(HttpResponseMessage response)
   at Tests.Test /razor returns html content()
Total tests: 5. Passed: 4. Failed: 1. Skipped: 0.
Test execution time: 4.4700 Seconds
Test Run Failed.

```

**Comment by TheAngryByrd** [comment]
And of course I can't reproduce the CI error on osx or mint. ☹️

**Comment by TheAngryByrd** [comment]
```
 System.Exception : "One or more errors occurred. (The directory name /home/travis/build/dustinmoris/Giraffe/samples/SampleApp/SampleApp.Tests/bin/Debug/netcoreapp1.1/views/ is invalid.
Parameter name: path)"
```

I bet it's case sensitivity.

**Comment by TheAngryByrd** [comment]
Getting closer 

```
 System.Exception : "One or more errors occurred. (Could not find view with the name 'Person')"
```

**Comment by TheAngryByrd** [comment]
Looks like they're still debating this nonsense https://github.com/aspnet/Mvc/issues/4426.  Gonna hack around the issue by forcing it all to `/Views`

**Comment by TheAngryByrd** [comment]
TA DA!

**Comment by TheAngryByrd** [comment]
Finally stood up a windows box.  Since we're now getting a better error message with `ensureSuccess`.  This is what the error I'm getting when using `xunit` `2.3.0-beta*`

```
System.Exception : "System.AggregateException: One or more errors occurred. (One or more errors occurred. (An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.)) ---> System.AggregateException: One or more errors occurred. (An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.) ---> System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor..ctor(IServiceProvider services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.DataProtection.SimpleActivator.CreateInstance(Type expectedBaseType, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.ActivatorExtensions.CreateInstance[T](IActivator activator, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.) ---> System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor..ctor(IServiceProvider services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.DataProtection.SimpleActivator.CreateInstance(Type expectedBaseType, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.ActivatorExtensions.CreateInstance[T](IActivator activator, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__15.MoveNext()
Test Run Failed.

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
---> (Inner Exception #0) System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor..ctor(IServiceProvider services)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.DataProtection.SimpleActivator.CreateInstance(Type expectedBaseType, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.ActivatorExtensions.CreateInstance[T](IActivator activator, String implementationTypeName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyEncryptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.<HandleSignInAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignInAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignInAsync>d__14.MoveNext()<---
<---
"
Stack Trace:
   at Microsoft.FSharp.Core.ExtraTopLevelOperators.PrintFormatToStringThenFail@148-1.Invoke(String message)
   at Tests.Test /user/{id} returns success when logged in as user()

```

**Comment by dustinmoris** [comment]
Awesome works, thanks again!

**Pull request merged**
