### PR TITLE
Lightweight policy based authorization

### PR DESCRIPTION
**Pull request by draganjovanovic1**
#123

### CODE REVIEW

**Comment by nojaf** [comment]
@draganjovanovic1 @dustinmoris aren't we missing unit tests here?

**Comment by dustinmoris** [comment]
Yeah I'll add it before releasing!

On 2 Nov 2017 09:21, "Florian Verdonck" <notifications@github.com> wrote:

@draganjovanovic1 <https://github.com/draganjovanovic1> @dustinmoris
<https://github.com/dustinmoris> aren't we missing unit tests here?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dustinmoris/Giraffe/pull/128#issuecomment-341404587>,
or mute the thread

**Comment by draganjovanovic1** [comment]
@nojaf, yes you are right, also all the existing auth handler are missing tests. @dustinmoris, I can make pull request with unit tests. Let's agree not to do the same job :) 

BTW Have you thought about using FsCheck?

**Comment by dustinmoris** [comment]
Hey, sure if you want to provide a PR that would be awesome. Regarding FsCheck how do you think it would add value to the current tests? Is it not more suitable for property based testing which is good for algorithms but maybe less for very specific authentication scenarios? I might be misunderstanding the library though so if you have more experience and could explain the benefit of it that it would be great.

**Comment by forki** [comment]
Property based testing is introduced for testing of algorithms and
protocols. Because these are usually the hardest things to tests. But it
turns out they are valuable for most other things as well.

Am 06.11.2017 04:07 schrieb "Dustin Moris Gorski" <notifications@github.com
>:

Hey, sure if you want to provide a PR that would be awesome. Regarding
FsCheck how do you think it would add value to the current tests? Is it not
more suitable for property based testing which is good for algorithms but
maybe less for very specific authentication scenarios? I might be
misunderstanding the library though so if you have more experience and
could explain the benefit of it that it would be great.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dustinmoris/Giraffe/pull/128#issuecomment-342035081>,
or mute the thread

**Pull request merged**
